dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=notify

matrix:
  include:
    # Android
    # - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    # - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=i686-linux-android DISABLE_TESTS=1
    - env: TARGET=x86_64-linux-android

    # iOS
    # - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
    #   os: osx
    # - env: TARGET=armv7-apple-ios DISABLE_TESTS=1
    #   os: osx
    # - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1
    #   os: osx
    # - env: TARGET=i386-apple-ios DISABLE_TESTS=1
    #   os: osx
    - env: TARGET=x86_64-apple-ios
      os: osx

    # Linux
    # - env: TARGET=aarch64-unknown-linux-gnu
    # - env: TARGET=arm-unknown-linux-gnueabi
    # - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=i686-unknown-linux-musl
    # - env: TARGET=mips-unknown-linux-gnu
    # - env: TARGET=mips64-unknown-linux-gnuabi64
    # - env: TARGET=mips64el-unknown-linux-gnuabi64
    # - env: TARGET=mipsel-unknown-linux-gnu
    # - env: TARGET=powerpc-unknown-linux-gnu
    # - env: TARGET=powerpc64-unknown-linux-gnu
    # - env: TARGET=powerpc64le-unknown-linux-gnu
    # - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd
    - env: TARGET=x86_64-unknown-freebsd
    - env: TARGET=x86_64-unknown-netbsd

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

    # Beta on all Tier 1 (fast builds)
    - env: NO_CROSS=1
      rust: beta
      sudo: false
      services: false
    - env: NO_CROSS=1
      os: osx
      rust: beta
      sudo: false
      services: false

    # Nightly on Linux (fast build)
    - env: NO_CROSS=1
      rust: nightly
      sudo: false
      services: false

before_install:
  - set -e
  - rustup self update

install:
  - |
    if [[ -z "$NO_CROSS" ]]; then
      sh ci/install.sh
      source ~/.cargo/env || true
    fi

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    # - /^v\d+\.\d+\.\d+.*$/
    # - master
    - next

# notifications:
#   email:
#     on_success: never
