dist: xenial
language: rust
services: docker

env:
  global:
    - CRATE_NAME=notify
    - RUSTFLAGS=-Awhere_clauses_object_safety
    # https://github.com/rust-lang/rust/issues/51443 for AnyMap

matrix:
  fast_finish: true
  include:

    # Audit only
    - env: CARGO_AUDIT=1

    # Windows: first as they take longest
    - env: NO_CROSS=1
      os: windows
      rust: nightly
    - env: NO_CROSS=1
      os: windows
      rust: 1.31.1
    - env: NO_CROSS=1
      os: windows

    # Linux: container, fast
    - env: NO_CROSS=1
      rust: nightly
    - env: NO_CROSS=1
      rust: 1.31.1
    - env: NO_CROSS=1

    # macOS: services not supported
    - env: NO_CROSS=1
      os: osx
      rust: nightly
    - env: NO_CROSS=1
      os: osx
      rust: 1.31.1
    - env: NO_CROSS=1
      os: osx

    # Clippy only
    - env: CARGO_CLIPPY=1

    # Tested, but no Tier 1 support (cross-compiles)
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=i686-apple-darwin
      os: osx
    # above list are candidates for emulation-less build/test (architecture is compatible)
    # but require a lot more fiddling to figure out the correct travis incantation
    # perhaps a lead: https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test

    - env: TARGET=x86_64-linux-android
    - env: TARGET=x86_64-apple-ios
      os: osx
    - env: TARGET=i386-apple-ios
      os: osx

    # Builds only, no tests (cross-compiles)
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1

  allow_failures:
    - env: CARGO_CLIPPY=1

    # From the not-Tier-1 list
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-freebsd
    - env: TARGET=x86_64-linux-android
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-apple-ios
    - env: TARGET=i386-apple-ios
    - env: TARGET=i686-apple-darwin

    # From the no-tests list
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1

    # List of other potential platforms

    # Android
    # - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    # - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=i686-linux-android DISABLE_TESTS=1

    # iOS
    # - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
    #   os: osx
    # - env: TARGET=armv7-apple-ios DISABLE_TESTS=1
    #   os: osx
    # - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1
    #   os: osx

    # Linux
    # - env: TARGET=aarch64-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_TESTS=1
    # - env: TARGET=mips-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=mips64-unknown-linux-gnuabi64 DISABLE_TESTS=1
    # - env: TARGET=mips64el-unknown-linux-gnuabi64 DISABLE_TESTS=1
    # - env: TARGET=mipsel-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=powerpc-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=powerpc64-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=powerpc64le-unknown-linux-gnu DISABLE_TESTS=1
    # - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1

before_install:
  - set -e
  - |
    if [ $TRAVIS_OS_NAME = windows ]; then
        choco install windows-sdk-10.0
    fi
    if [[ ! -z "$CARGO_AUDIT" || ! -z "$CARGO_CLIPPY" ]]; then
      which cargo-audit || cargo install --debug cargo-audit
    fi
# --debug for faster build at the minimal expense of runtime speed

install:
  - |
    if [[ -z "$NO_CROSS" && -z "$CARGO_AUDIT" && -z "$CARGO_CLIPPY" ]]; then
      sh ci/install.sh
      source ~/.cargo/env || true
    fi

script:
  - |
    if [[ ! -z "$CARGO_AUDIT" ]]; then
      cargo check
      cargo audit
    elif [[ ! -z "$CARGO_CLIPPY" ]]; then
      cargo clippy
    else
      bash ci/script.sh
    fi

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    # - /^v\d+\.\d+\.\d+.*$/

    # test branches
    - /^try-/

    # main branches
    # - main
    - next

# notifications:
#   email:
#     on_success: never
