[package]
authors = ["Félix Saparelli <felix@passcod.name>"]
name = "notify"
version = "6.0.0-alpha.1"

[workspace]
members = [
  "backend",
  # "backend-poll",
  # "backend-inotify",
  # "backend-kqueue",
]

[dependencies]
futures-preview = "0.3.0-alpha.13"

[dependencies.notify-backend]
path = "./backend"

# [target.'cfg(target_os="linux")'.dependencies.notify-backend-inotify]
# path = "./backend-inotify"
#
# [target.'cfg(target_os="android")'.dependencies.notify-backend-inotify]
# path = "./backend-inotify"

# [target.'cfg(target_os="dragonfly")'.dependencies.notify-backend-kqueue]
# path = "./backend-kqueue"
#
# [target.'cfg(target_os="freebsd")'.dependencies.notify-backend-kqueue]
# path = "./backend-kqueue"
#
# [target.'cfg(target_os="netbsd")'.dependencies.notify-backend-kqueue]
# path = "./backend-kqueue"
#
# [target.'cfg(target_os="openbsd")'.dependencies.notify-backend-kqueue]
# path = "./backend-kqueue"

# [dependencies.notify-backend-poll]
# path = "./backend-poll"
