[package]
name = "notify"
version = "2.5.5"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Gilbert Röhrbein <gilbert@ifsr.de>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
  "Michael Maurizi <michael.maurizi@gmail.com>",
  "Pierre Baillet <oct@zoy.org>",
  "ShuYu Wang <andelf@gmail.com>",
  "Jimmy Lu <gongchuo.lu@gmail.com>",
  "Francisco Giordano <frangio.1@gmail.com>",
  "Jake Kerr",
  "Ty Overby <ty@pre-alpha.com>",
  "John Quigley <veggieburritox@gmail.com>"
]

description = "Cross-platform filesystem notification library"
homepage = "https://github.com/passcod/rsnotify"
repository = "https://github.com/passcod/rsnotify.git"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "events",
  "filesystem",
  "notify",
  "watch",
]

[dependencies]
bitflags = "^0.4.0"
libc = "^0.2.4"
log = "^0.3.4"
time = "^0.1.34"
filetime = "^0.1.9"
walkdir = "^0.1.5"

[target.'cfg(target_os="linux")'.dependencies]
inotify = "^0.2.3"
mio = "^0.5.0"

[target.'cfg(target_os="macos")'.dependencies]
fsevent = "^0.2.11"
fsevent-sys = "^0.1.3"

[target.'cfg(windows)'.dependencies]
winapi = "^0.2.5"
kernel32-sys = "^0.2.1"

[dev-dependencies]
tempfile = "^2.0.1"
tempdir = "^0.3.4"
