[package]
name = "notify"
version = "1.1.3"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
]

description = "Cross-platform filesystem notification library"
homepage = "https://github.com/passcod/rsnotify"
repository = "https://github.com/passcod/rsnotify"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "events",
  "filesystem",
  "notify",
  "watch",
]

[dependencies]
time = "*"

#[target.x86_64-unknown-linux-gnu.dependencies.inotify]
#version = "0.1"

[target.x86_64-unknown-linux-gnu.dependencies.inotify]
git = "https://github.com/blaenk/inotify-rs.git"
branch = "new-io"
