[package]
name = "notify"
version = "2.3.3"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Gilbert Röhrbein <gilbert@ifsr.de>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
  "Michael Maurizi <mmaurizi@azavea.com>",
  "Pierre Baillet <oct@zoy.org>",
  "ShuYu Wang <andelf@gmail.com>",
  "Jimmy Lu <gongchuo.lu@gmail.com>",
  "Francisco Giordano <frangio.1@gmail.com>",
  "Jake Kerr",
  "Ty Overby <ty@pre-alpha.com>",
]

description = "Cross-platform filesystem notification library"
homepage = "https://github.com/passcod/rsnotify"
repository = "https://github.com/passcod/rsnotify.git"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "events",
  "filesystem",
  "notify",
  "watch",
]

[dependencies]
bitflags = "*"
libc = "*"
log = "*"
time = "*"
filetime = "*"
walker = "^1.0.0"

[target.x86_64-unknown-linux-gnu.dependencies.inotify]
version = "^0.1"

[target.x86_64-apple-darwin.dependencies.fsevent]
version = "^0.2.11"

[target.x86_64-apple-darwin.dependencies.fsevent-sys]
version = "^0.1"

[dev-dependencies]
tempfile = "^1.1.0"
tempdir = "^0.3.4"
