[package]
name = "notify"
version = "0.0.1"
authors = ["Félix Saparelli <felix@passcod.name>"]

[dependencies]
time = "*"
#inotify = "*"

[dependencies.inotify]
git = "https://github.com/hannobraun/inotify-rs.git"
