[package]
authors = ["Félix Saparelli <felix@passcod.name>"]
name = "notify"
version = "5.0.0-alpha.1"

[dependencies]

[dependencies.notify-backend]
path = "./backend"

[target.'cfg(target_os="linux")'.dependencies.notify-backend-inotify]
path = "./backend-inotify"

[target.'cfg(target_os="freebsd")'.dependencies.notify-backend-kqueue]
path = "./backend-kqueue"

[dependencies.notify-backend-poll-tree]
path = "./backend-poll-tree"

[workspaces]
