[package]
authors = ["Félix Saparelli <felix@passcod.name>"]
name = "notify"
version = "5.0.0-alpha.1"

[dependencies]

[dependencies.notify-backend]
path = "./backend"

[dependencies.notify-backend-inotify]
path = "./backend-inotify"

[workspaces]
